version: '3'

services:
  postgres:
      image:  postgres:15
      volumes:
        - /Users/csmaniotto/datadir/pgsql:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: "csmaniotto"
        POSTGRES_PASSWORD: "carlos123"
      networks:
              - internal_lan
              - external_lan
      ports:
        - 5432:5432
  app:
    build: .
    volumes:
       - .:/home/user_app/app
    environment:
        DEBUG: True
        PGDB: "project_core"
        PGUSER: "csmaniotto"
        PGPASSWORD: "carlos123"
        PGHOST: "postgres"
        PGPORT: "5432"
        PG_POOL_MIN_SIZE: 2
        PG_POOL_MAX_SIZE: 500
        PG_POOL_TIMEOUT: 10
        LANGUAGE_CODE: "pt-br"
        TIME_ZONE: "UTC"
        HEADER_TITLE: "3cord.AI - SmartMon 📈📊🥸 "
        SECRET_KEY: "'SuperSman_at_3cord_ay%^)js1c%zxz^h$rft5%w712pr$4j9h1n4u%tr&4jt&mtjls3'"
    networks:
            - internal_lan
            - external_lan
    ports:
      - 8000:8000

networks:
  internal_lan:
    name: internal_lan
  external_lan:
    #external: true
    name: external_lan
    driver: bridge
